<?php

/*
|--------------------------------------------------------------------------
| Catálogos de dominio RIPS / SGSSS (Colombia)
|--------------------------------------------------------------------------
| Portados desde las constantes globales del config/app.php legacy.
| Acceso: config('sispam.tipos_documento')
*/

return [

    'tipos_documento' => [
        'CC' => 'Cédula de Ciudadanía',
        'CE' => 'Cédula de Extranjería',
        'PA' => 'Pasaporte',
        'TI' => 'Tarjeta de Identidad',
        'RC' => 'Registro Civil',
        'PEP' => 'Permiso Especial de Permanencia',
        'PPT' => 'Permiso por Protección Temporal',
        'NV' => 'Nacido Vivo',
    ],

    'eps_colombia' => [
        'Sura EPS',
        'Savia Salud EPS',
        'Nueva EPS',
        'Sanitas EPS',
        'Compensar EPS',
        'Salud Total EPS',
        'Capital Salud EPS',
        'Asmet Salud EPS',
        'Famisanar EPS',
        'Coosalud EPS',
        'Mutual Ser EPS',
        'Mallamas EPS',
        'Pijaos Salud EPS',
        'Capresoca EPS',
        'Aliansalud EPS',
        'EPM - Empresas Públicas de Medellín',
        'Fuerzas Militares / Policía Nacional',
        'Particular / Sin EPS',
    ],

    'ips_antioquia' => [
        'Hospital Pablo Tobón Uribe',
        'Hospital Universitario San Vicente Fundación',
        'Clínica Las Américas Auna',
        'Clínica León XIII (IPS Universitaria)',
        'Clínica Medellín (Sede Centro / El Poblado)',
        'Clínica Rosario (Sede El Tesoro / Centro)',
        'Hospital General de Medellín E.S.E.',
        'Clínica CardioVID',
        'Clínica CES (Sede Prado / Almacentro)',
        'Clínica Clofan',
        'Clínica Soma',
        'Hospital Manuel Uribe Ángel (Envigado)',
        'Hospital San Rafael (Itagüí)',
        'Hospital Marco Fidel Suárez (Bello)',
        'Hospital San Juan de Dios (Rionegro)',
        'Clínica Somer (Rionegro)',
        'Hospital San Juan de Dios (La Ceja)',
        'Hospital San Juan de Dios (Marinilla)',
        'Hospital San Juan de Dios (Santa Fe de Antioquia)',
        'Hospital San Vicente de Paúl (Caldas)',
        'Hospital Venancio Díaz Díaz (Sabaneta)',
        'Hospital Nuestra Señora de la Candelaria (Guarne)',
        'Hospital San Juan de Dios (Yarumal)',
        'Hospital Antonio Roldán Betancur (Apartadó)',
        'IPS Comfama (Distintas Sedes Antioquia)',
        'IPS Comfenalco Antioquia',
        'IPS Sura (Distintas Sedes Antioquia)',
        'IPS Promedan',
        'IPS Viva 1A',
        'Metrosalud E.S.E. (Red Municipal Medellín)',
        'Comité de Estudios Médicos S.A.S.',
        'Otra IPS / Centro de Salud de Antioquia',
    ],

    'tipos_doc_adjunto' => [
        'CEDULA' => 'Cédula / Doc. Identidad',
        'AUTORIZACION' => 'Autorización de Servicios',
        'ORDEN_MEDICA' => 'Fórmula / Orden Médica',
        'HISTORIA_CLINICA' => 'Historia Clínica / Anexo',
        'OTRO' => 'Otro Documento',
    ],

    'sedes_atencion' => [
        'Sede Prado',
        'Sede Ayacucho',
        'Sede Centro',
        'Sede Poblado',
        'Sede Laureles',
        'Sede Belén',
        'Sede Robledo',
    ],

    'estados_civiles' => [
        'Soltero(a)',
        'Casado(a)',
        'Unión Libre',
        'Divorciado(a)',
        'Viudo(a)',
    ],

    'grupos_poblacionales' => [
        'Otro Grupo Poblacional',
        'Indigente / Habitante de Calle',
        'Población ROM (Gitana)',
        'Población Raizal',
        'Población Palenquera',
        'Población Afrocolombiana',
        'Víctima del Conflicto / Desplazado',
        'Adulto Mayor',
        'Persona en Reincorporación',
    ],

    'grupos_etnicos' => [
        'No Aplica',
        'Afrocolombiano',
        'Gitano (ROM)',
        'Indígena',
        'Palenquero',
        'Raizal',
    ],

    'tipos_discapacidad' => [
        'No Aplica',
        'Auditiva',
        'Física',
        'Visual',
        'Intelectual',
        'Mental / Psicosocial',
        'Múltiple',
    ],

    'tipos_escolaridad' => [
        'NA',
        'Preescolar',
        'Básica Primaria',
        'Básica Secundaria',
        'Media',
        'Técnica / Tecnológica',
        'Universitaria',
        'Postgrado',
    ],

    'barrios_medellin' => [
        'El Poblado',
        'Laureles',
        'Belén',
        'Aranjuez',
        'Robledo',
        'Manrique',
        'Buenos Aires',
        'San Javier',
        'Castilla',
        'Doce de Octubre',
        'Villa Hermosa',
        'Candelaria (Centro)',
        'Guayabal',
        'La América',
        'Santa Cruz',
        'Popular',
        'San Antonio de Prado',
        'San Cristóbal',
        'Santa Elena',
        'Altavista',
        'Palmitas',
        'Otro Barrio',
    ],

    'municipios_antioquia' => [
        'MEDELLIN-ANT-05001',
        'BELLO-ANT-05088',
        'ITAGUI-ANT-05360',
        'ENVIGADO-ANT-05266',
        'SABANETA-ANT-05631',
        'CALDAS-ANT-05129',
        'LA ESTRELLA-ANT-05380',
        'RIONEGRO-ANT-05615',
        'APARTADO-ANT-05045',
        'TURBO-ANT-05837',
        'CAUCASIA-ANT-05154',
        'CHIGORODO-ANT-05172',
        'GIRARDOTA-ANT-05308',
        'COPACABANA-ANT-05212',
        'MARINILLA-ANT-05440',
        'GUARNE-ANT-05318',
        'SANTA FE DE ANTIOQUIA-ANT-05042',
        'YARUMAL-ANT-05887',
        'EL CARMEN DE VIBORAL-ANT-05148',
        'LA CEJA-ANT-05376',
        'PUERTO BERRIO-ANT-05579',
    ],

    'ocupaciones' => [
        'Abogado',
        'Agente de Viajes',
        'Agricultor',
        'Ama de Casa',
        'Arquitecto',
        'Comerciante',
        'Contador',
        'Docente / Profesor',
        'Estudiante',
        'Enfermero(a)',
        'Ingeniero(a)',
        'Médico(a)',
        'Pensionado(a)',
        'Independiente',
        'Empleado',
        'Desempleado',
        'Técnico(a)',
        'Operario(a)',
        'Conductor(a)',
        'Vigilante / Seguridad',
        'Servidor Público',
        'Otro',
    ],

    'tipos_afiliado' => [
        'Contributivo Cotizante',
        'Contributivo Beneficiario',
        'Contributivo Adicional',
        'Subsidiado',
        'Vinculado',
        'Particular',
        'Especial / Excepción',
    ],

    'niveles_socioeconomicos' => [
        'CATEGORIA A',
        'CATEGORIA B',
        'CATEGORIA C',
        'SIN CATEGORIA',
    ],

    'opciones_prioridad' => [
        'NORMAL' => 'Normal (Atención Estándar)',
        'TERCERA_EDAD' => '👴 Tercera Edad / Adulto Mayor',
        'EMBARAZADA' => '🤰 Mujer Embarazada / Gestante',
        'DISCAPACIDAD' => '♿ Persona con Discapacidad',
        'NIÑO_LACTANTE' => '👶 Niño / Lactante',
        'OTRO_PREFERENCIAL' => '⭐ Otro Caso Preferencial',
    ],

];
